// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QRMenu.Data.Data;

#nullable disable

namespace QRMenu.Data.Migrations
{
    [DbContext(typeof(QRMenuDbContext))]
    [Migration("20260411212625_AddOyunVeIndirim")]
    partial class AddOyunVeIndirim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KayitId")
                        .HasColumnType("integer");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("TabloAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLoglar", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Bolgeler");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.HappyHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IndirimOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("HappyHour", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.HappyHourUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HappyHourId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("HappyHourId", "UrunId")
                        .IsUnique();

                    b.ToTable("HappyHourUrunler", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdEN")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sıcak İçecekler",
                            AdEN = "Hot Beverages",
                            AktifMi = true,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Soğuk İçecekler",
                            AdEN = "Cold Beverages",
                            AktifMi = true,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Atıştırmalıklar",
                            AdEN = "Snacks",
                            AktifMi = true,
                            SiraNo = 3
                        });
                });

            modelBuilder.Entity("QRMenu.Core.Entities.KazanilanIndirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("KazanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdulTanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UgulananIndirimTutari")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("KazanilanIndirimler");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Kullanici", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Masa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("BolgeId")
                        .HasColumnType("integer");

                    b.Property<int>("MasaNo")
                        .HasColumnType("integer");

                    b.Property<string>("QrKodUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.HasIndex("MasaNo")
                        .IsUnique();

                    b.ToTable("Masalar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            MasaNo = 1
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            MasaNo = 2
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = true,
                            MasaNo = 3
                        },
                        new
                        {
                            Id = 4,
                            AktifMi = true,
                            MasaNo = 4
                        },
                        new
                        {
                            Id = 5,
                            AktifMi = true,
                            MasaNo = 5
                        });
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OdemeTipi")
                        .HasColumnType("integer");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("Odemeler", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Opsiyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdEN")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("EkFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Grup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GrupEN")
                        .HasColumnType("text");

                    b.Property<bool>("Zorunlu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Opsiyonlar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Küçük",
                            AdEN = "Small",
                            EkFiyat = 0m,
                            Grup = "Boyut",
                            Zorunlu = true
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Orta",
                            AdEN = "Medium",
                            EkFiyat = 10.00m,
                            Grup = "Boyut",
                            Zorunlu = true
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Büyük",
                            AdEN = "Large",
                            EkFiyat = 20.00m,
                            Grup = "Boyut",
                            Zorunlu = true
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Tam Yağlı Süt",
                            AdEN = "Whole Milk",
                            EkFiyat = 0m,
                            Grup = "Süt Tipi",
                            Zorunlu = true
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Yağsız Süt",
                            AdEN = "Skim Milk",
                            EkFiyat = 0m,
                            Grup = "Süt Tipi",
                            Zorunlu = true
                        });
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Oturum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<bool>("Kullanildi")
                        .HasColumnType("boolean");

                    b.Property<int>("MasaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SonIslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi")
                        .HasDatabaseName("IX_Oturumlar_AktifMi");

                    b.HasIndex("MasaId");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_Oturumlar_TokenHash");

                    b.ToTable("Oturumlar", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.OyunAyar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OyunAyarlar");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.OyunOdul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IhtimalYuzdesi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IndirimYuzdesi")
                        .HasColumnType("numeric");

                    b.Property<string>("OdulTanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OyunAyarId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OyunAyarId");

                    b.ToTable("OyunOduller");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OturumId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OturumId")
                        .IsUnique();

                    b.ToTable("Sepetler", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.SepetDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SeciliOpsiyonlar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SepetId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.HasIndex("UrunId");

                    b.ToTable("SepetDetaylar", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MasaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OturumId")
                        .HasColumnType("integer");

                    b.Property<bool>("OyunOynandiMi")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_Siparisler_Durum");

                    b.HasIndex("MasaId")
                        .HasDatabaseName("IX_Siparisler_MasaId");

                    b.HasIndex("OturumId");

                    b.ToTable("Siparisler", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.SiparisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("SeciliOpsiyonlar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisDetaylar", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AciklamaEN")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AdEN")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Kalori")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<bool>("PopulerMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SatisSayisi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi")
                        .HasDatabaseName("IX_Urunler_AktifMi");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Taze demlenmiş filtre kahve",
                            AciklamaEN = "Freshly brewed filter coffee",
                            Ad = "Filtre Kahve",
                            AdEN = "Filter Coffee",
                            AktifMi = true,
                            Fiyat = 45.00m,
                            KategoriId = 1,
                            PopulerMi = true,
                            SatisSayisi = 150
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Espresso ve sütlü kahve",
                            AciklamaEN = "Espresso with steamed milk",
                            Ad = "Latte",
                            AdEN = "Latte",
                            AktifMi = true,
                            Fiyat = 65.00m,
                            KategoriId = 1,
                            PopulerMi = true,
                            SatisSayisi = 200
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Espresso ve sıcak su",
                            AciklamaEN = "Espresso with hot water",
                            Ad = "Americano",
                            AdEN = "Americano",
                            AktifMi = true,
                            Fiyat = 50.00m,
                            KategoriId = 1,
                            PopulerMi = false,
                            SatisSayisi = 80
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Geleneksel Türk kahvesi",
                            AciklamaEN = "Traditional Turkish coffee",
                            Ad = "Türk Kahvesi",
                            AdEN = "Turkish Coffee",
                            AktifMi = true,
                            Fiyat = 40.00m,
                            KategoriId = 1,
                            PopulerMi = false,
                            SatisSayisi = 120
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Soğuk süt ve espresso",
                            AciklamaEN = "Cold milk and espresso",
                            Ad = "Buzlu Latte",
                            AdEN = "Iced Latte",
                            AktifMi = true,
                            Fiyat = 70.00m,
                            KategoriId = 2,
                            PopulerMi = true,
                            SatisSayisi = 180
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Taze sıkılmış limonata",
                            AciklamaEN = "Freshly squeezed lemonade",
                            Ad = "Limonata",
                            AdEN = "Lemonade",
                            AktifMi = true,
                            Fiyat = 55.00m,
                            KategoriId = 2,
                            PopulerMi = false,
                            SatisSayisi = 90
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Karışık meyveli smoothie",
                            AciklamaEN = "Mixed fruit smoothie",
                            Ad = "Smoothie",
                            AdEN = "Smoothie",
                            AktifMi = false,
                            Fiyat = 75.00m,
                            KategoriId = 2,
                            PopulerMi = false,
                            SatisSayisi = 60
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "New York usulü cheesecake",
                            AciklamaEN = "New York style cheesecake",
                            Ad = "Cheesecake",
                            AdEN = "Cheesecake",
                            AktifMi = true,
                            Fiyat = 90.00m,
                            KategoriId = 3,
                            PopulerMi = true,
                            SatisSayisi = 160
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Çikolatalı brownie",
                            AciklamaEN = "Chocolate brownie",
                            Ad = "Brownie",
                            AdEN = "Brownie",
                            AktifMi = true,
                            Fiyat = 70.00m,
                            KategoriId = 3,
                            PopulerMi = false,
                            SatisSayisi = 95
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Tavuklu kulüp sandviç",
                            AciklamaEN = "Chicken club sandwich",
                            Ad = "Sandviç",
                            AdEN = "Sandwich",
                            AktifMi = true,
                            Fiyat = 110.00m,
                            KategoriId = 3,
                            PopulerMi = false,
                            SatisSayisi = 70
                        });
                });

            modelBuilder.Entity("QRMenu.Core.Entities.UrunGorsel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunGorseller", (string)null);
                });

            modelBuilder.Entity("QRMenu.Core.Entities.UrunOpsiyon", b =>
                {
                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<int>("OpsiyonId")
                        .HasColumnType("integer");

                    b.HasKey("UrunId", "OpsiyonId");

                    b.HasIndex("OpsiyonId");

                    b.ToTable("UrunOpsiyonlar", (string)null);

                    b.HasData(
                        new
                        {
                            UrunId = 1,
                            OpsiyonId = 1
                        },
                        new
                        {
                            UrunId = 1,
                            OpsiyonId = 2
                        },
                        new
                        {
                            UrunId = 1,
                            OpsiyonId = 3
                        },
                        new
                        {
                            UrunId = 2,
                            OpsiyonId = 1
                        },
                        new
                        {
                            UrunId = 2,
                            OpsiyonId = 2
                        },
                        new
                        {
                            UrunId = 2,
                            OpsiyonId = 3
                        },
                        new
                        {
                            UrunId = 2,
                            OpsiyonId = 4
                        },
                        new
                        {
                            UrunId = 2,
                            OpsiyonId = 5
                        },
                        new
                        {
                            UrunId = 3,
                            OpsiyonId = 1
                        },
                        new
                        {
                            UrunId = 3,
                            OpsiyonId = 2
                        },
                        new
                        {
                            UrunId = 3,
                            OpsiyonId = 3
                        },
                        new
                        {
                            UrunId = 5,
                            OpsiyonId = 1
                        },
                        new
                        {
                            UrunId = 5,
                            OpsiyonId = 2
                        },
                        new
                        {
                            UrunId = 5,
                            OpsiyonId = 3
                        },
                        new
                        {
                            UrunId = 5,
                            OpsiyonId = 4
                        },
                        new
                        {
                            UrunId = 5,
                            OpsiyonId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRMenu.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QRMenu.Core.Entities.HappyHour", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.HappyHourUrun", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.HappyHour", "HappyHour")
                        .WithMany("HappyHourUrunler")
                        .HasForeignKey("HappyHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRMenu.Core.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HappyHour");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.KazanilanIndirim", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Siparis", "Siparis")
                        .WithMany("KazanilanIndirimler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Masa", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Bolge", "Bolge")
                        .WithMany("Masalar")
                        .HasForeignKey("BolgeId");

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Odeme", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Siparis", "Siparis")
                        .WithMany("Odemeler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Oturum", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Masa", "Masa")
                        .WithMany("Oturumlar")
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Masa");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.OyunOdul", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.OyunAyar", "OyunAyar")
                        .WithMany("Oduller")
                        .HasForeignKey("OyunAyarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OyunAyar");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Sepet", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Oturum", "Oturum")
                        .WithOne("Sepet")
                        .HasForeignKey("QRMenu.Core.Entities.Sepet", "OturumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oturum");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.SepetDetay", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Sepet", "Sepet")
                        .WithMany("SepetDetaylar")
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRMenu.Core.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sepet");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Siparis", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Masa", "Masa")
                        .WithMany("Siparisler")
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QRMenu.Core.Entities.Oturum", "Oturum")
                        .WithMany()
                        .HasForeignKey("OturumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Masa");

                    b.Navigation("Oturum");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.SiparisDetay", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Siparis", "Siparis")
                        .WithMany("SiparisDetaylar")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRMenu.Core.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Urun", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.UrunGorsel", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.UrunOpsiyon", b =>
                {
                    b.HasOne("QRMenu.Core.Entities.Opsiyon", "Opsiyon")
                        .WithMany("UrunOpsiyonlar")
                        .HasForeignKey("OpsiyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRMenu.Core.Entities.Urun", "Urun")
                        .WithMany("UrunOpsiyonlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opsiyon");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Bolge", b =>
                {
                    b.Navigation("Masalar");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.HappyHour", b =>
                {
                    b.Navigation("HappyHourUrunler");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Masa", b =>
                {
                    b.Navigation("Oturumlar");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Opsiyon", b =>
                {
                    b.Navigation("UrunOpsiyonlar");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Oturum", b =>
                {
                    b.Navigation("Sepet");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.OyunAyar", b =>
                {
                    b.Navigation("Oduller");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Sepet", b =>
                {
                    b.Navigation("SepetDetaylar");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Siparis", b =>
                {
                    b.Navigation("KazanilanIndirimler");

                    b.Navigation("Odemeler");

                    b.Navigation("SiparisDetaylar");
                });

            modelBuilder.Entity("QRMenu.Core.Entities.Urun", b =>
                {
                    b.Navigation("UrunOpsiyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
